name: Docker

on:
  push:
    branches:
      - docker
    tags:
      - v*

env:
  IMAGE_NAME: rayyansys/prisma-flowdiagram-shinyapp

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Determine target image name
        id: image-name
        run: |
          IMAGE_ID=ghcr.io/$IMAGE_NAME

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "docker" ] && VERSION=latest

          IMAGES=
          IMAGES="$IMAGE_ID:$VERSION"$'\n'$IMAGES

          # debug output
          echo images $IMAGES
          echo ::set-output name=images::"$IMAGES"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.image-name.outputs.images }}
